### ISSUE TITLE
Can't run this on WINDOWS-PREVIEW@0.3.0 version

### ISSUE THREAD

**Issue by nzmedet** [atoy40/meteor-polymer-music#1]
```
Your app is crashing. Here's the latest log.
 C:\Users\admin\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
                    throw(ex);
                          ^
TypeError: Arguments to path.resolve must be strings
at Object.exports.resolve (path.js:116:15)
at Object.exports.relative (path.js:240:18)
at Package (packages/ecwyne:polymer/polymer.js:21:1)
at G:\meteor\music\meteor-polymer-music\.meteor\local\build\programs\server\packages\ecwyne_polymer.js:50:4
at G:\meteor\music\meteor-polymer-music\.meteor\local\build\programs\server\packages\ecwyne_polymer.js:57:3
at G:\meteor\music\meteor-polymer-music\.meteor\local\build\programs\server\boot.js:222:10
at Array.forEach (native)
at Function._.each._.forEach (C:\Users\admin\AppData\Local\.meteor\packages\meteor-tool\1.1.1-win.7\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
at G:\meteor\music\meteor-polymer-music\.meteor\local\build\programs\server\boot.js:117:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

**Comment by atoy40** [comment]
Not running on windows is not a bug, it's a feature.
Seriously ... i'll certainly never try to run my codes on windows .. but you're free to debug it and make pull request.

Anthony.
